import type { Employee } from "./types"

export const SAMPLE_EMPLOYEES: Employee[] = [
  {
    id: "emp-1",
    name: "Ahmed Ali",
    email: "ahmed@example.com",
    phone: "+20 100 111 2233",
    department: "IT",
    position: "Frontend Developer",
    status: "Active",
  },
  {
    id: "emp-2",
    name: "Sara Mohamed",
    email: "sara@example.com",
    phone: "+20 101 222 3344",
    department: "Marketing",
    position: "Marketing Specialist",
    status: "Active",
  },
  {
    id: "emp-3",
    name: "Omar Hassan",
    email: "omar@example.com",
    phone: "+20 102 333 4455",
    department: "HR",
    position: "HR Specialist",
    status: "On Leave",
  },
  {
    id: "emp-4",
    name: "Laila Ibrahim",
    email: "laila@example.com",
    phone: "+20 103 444 5566",
    department: "Finance",
    position: "Financial Analyst",
    status: "Active",
  },
  {
    id: "emp-5",
    name: "Youssef Adel",
    email: "youssef@example.com",
    phone: "+20 104 555 6677",
    department: "IT",
    position: "Backend Developer",
    status: "Active",
  },
  {
    id: "emp-6",
    name: "Nour Khaled",
    email: "nour@example.com",
    phone: "+20 105 666 7788",
    department: "Sales",
    position: "Sales Representative",
    status: "On Leave",
  },
  {
    id: "emp-7",
    name: "Mariam Fathy",
    email: "mariam@example.com",
    phone: "+20 106 777 8899",
    department: "Operations",
    position: "Operations Manager",
    status: "Active",
  },
  {
    id: "emp-8",
    name: "Karim Nabil",
    email: "karim@example.com",
    phone: "+20 107 888 9900",
    department: "IT",
    position: "DevOps Engineer",
    status: "Inactive",
  },
  {
    id: "emp-9",
    name: "Hana Samir",
    email: "hana@example.com",
    phone: "+20 108 999 0011",
    department: "Marketing",
    position: "Content Strategist",
    status: "Active",
  },
  {
    id: "emp-10",
    name: "Tarek Mostafa",
    email: "tarek@example.com",
    phone: "+20 109 000 1122",
    department: "Finance",
    position: "Accountant",
    status: "Active",
  },
  {
    id: "emp-11",
    name: "Dina Ashraf",
    email: "dina@example.com",
    phone: "+20 110 111 2233",
    department: "HR",
    position: "Recruiter",
    status: "Active",
  },
  {
    id: "emp-12",
    name: "Mostafa Gamal",
    email: "mostafa@example.com",
    phone: "+20 111 222 3344",
    department: "Sales",
    position: "Account Executive",
    status: "On Leave",
  },
]
